### ISSUE TITLE
Tagging rules example docu on operators is wrong

### ISSUE THREAD

**Issue by Strubbl** [wallabag/doc#104]
currently it is:

> domainName = "github.com"

But that does not work as expected. it should be

> domainName matches "github.com"

https://github.com/wallabag/doc/blob/master/en/user/configuration/tagging_rules.md

chat log reporting this issue:

> 04:57 <D347HxD> Hey, I'm trying to add some custom tags but they don't seem to be getting added to articles I add which should be hitting the fields to mark the tags.. here are the 3 that don't work:
> 04:58 <D347HxD> if « domainName = "digitalocean.com" » then tag as « digitaloceantutorials »                                
> 04:58 <D347HxD> if « content = "ubuntu" » then tag as « ubuntu »
> 04:58 <D347HxD> if « content = "docker" » then tag as « docker » 
> 11:23 <Strubbl> @D347HxD new tagging rules are only applied to the articles, which you are going to add afterwards, not for existing ones. 
> 16:51 <D347HxD> @Strubbl  that's what I mean. I added articles after making these tags that should trigger the content but they didn't get Tagged
> 16:52 <D347HxD> I added the docker install tutorial from digital ocean after making the tags for example. Nothing was added but all tags should have
> 17:35 <Strubbl> maybe you should try the "matches" operator instead of the equal
> 18:40 <D347HxD> So, like this? @Strubbl  https://i.godhub.xyz/07-07-2019-c3flZtmCK9.png
> 18:40 <D347HxD> but with github.com as digitalocean.com
> 18:42 <D347HxD> Yup, that worked. Thanks @Strubbl 
> 18:42 <D347HxD> Maybe this should be fixed as an example, as this is what got my using the = in the first place: https://i.godhub.xyz/07-07-2019-ePJIbbfsVe.png
> 18:43 <D347HxD> would the content also need to use matches? seems it doesnt work for =
> 18:45 <D347HxD> yup, content also needs to be matches and not =
> 18:45 <D347HxD> that should also be fixed in that instruction area

**Comment by j0k3r** [comment]
The doc is right FMPOV.
That's because `github.com` only respond to `http://github.com`.
Digitalocean always force the `www`. So I guess it should have used `domainName = "www. digitalocean.com"`

**Comment by jonas-hagen** [comment]
I was confused by this as well because it seemed that the tagging rules are not working. In the article view, the domain name appears as for example "theguardian.com":
![theguardian.com](https://user-images.githubusercontent.com/2494894/164943034-d90e460e-48ca-47b5-b908-640bbf306887.png)
But the rule needs to be written as: if « domainName = "www.theguardian.com" » then tag as « theguardian, news »

A different example in the help text (including a subdomain like www) would clarify a lot IMHO.

**Comment by j0k3r** [comment]
Good idea, feel free to open a PR!

**Comment by jonas-hagen** [comment]
Here you go! I thought this was an easy one, despite all the translations.
