### ISSUE TITLE
Shared hosting documentation broken

### ISSUE THREAD

**Issue by cpda11** [wallabag/doc#114]
For shared hosting, the current documentation references a package to pull from `wllbg.org`. 

For this host, 

- the certificate is not matching
- the package is not available (404)

`wget https://wllbg.org/latest-v2-package && tar xvf latest-v2-package`

> https://github.com/wallabag/doc/blob/master/en/admin/installation/installation.md#on-shared-hosting

**Comment by Kdecherf** [comment]
This issue does not occur anymore, closing it
