### ISSUE TITLE
Caddy VirtualHosts needs updating for Caddy V2

### ISSUE THREAD

**Issue by wackydoo** [wallabag/doc#130]
I haven't been able to massage the caddy 1 virtual host configuration in [doc/virtualhosts.md](https://github.com/wallabag/doc/blob/master/en/admin/installation/virtualhosts.md) to work with caddy 2.
There have been slight changes in the CaddyFile format.

Does anyone have a working configuration to add to the docs?

**Comment by j0k3r** [comment]
I don't

**Comment by rEnr3n** [comment]
Looks easy to convert.

```
domain.tld {
  root * /var/www/wallabag/web
  file_server
  php_fastcgi unix//var/run/php7-fpm.sock {
    index app.php
  }
  try_files {path} {path}/ /app.php?{query}
  tls your@email.ru
  log {
    output file /var/log/caddy/wbg.access.log
  }
}
```

**Comment by wackydoo** [comment]
Confirmed that it works.  Thankyou!

**Comment by j0k3r** [comment]
Thanks @rEnr3n
