### ISSUE TITLE
Upgrade instructions for Self-Hosted instances missing

### ISSUE THREAD

**Issue by cukabeka** [wallabag/doc#166]
Hi, 
thanks for the product and the docs. I don't dare to upgrade to 2.5.2 from 2.4.2 because there is no hints on how to do that and what tables might have changed. I already managed 2.3.8 to 2.4.2, but for the recent version the guide is still missing.
Would be highly appreciated!

BTW, but not doc-related: Maybe a console PHP command for all these upgrades might be a good idea in the future?

**Comment by qwertygc** [comment]
Hello,

+1. With the 2.6.* version, it's impossible to update (maybe we need to write SQL script ?)

**Comment by j0k3r** [comment]
> it's impossible to update

What do you mean?

**Comment by qwertygc** [comment]
I'm on a shared server.

It seems to me that simply sending files by replacing parameters.yml is not enough, and that there are SQL queries to be made to upgrade from 2.5 to 2.6.1.

**Comment by nicosomb** [comment]
You have to execute `make update`

**Comment by qwertygc** [comment]
I can't execute a make update on a shared server. Document give [sql queries](https://doc.wallabag.org/fr/admin/query-upgrade-21-22.html) for 2.1 to 2.2. It's possible to have same page for 2.5 to 2.6 please ?

**Comment by nicosomb** [comment]
hmm ok sorry. We'll add the documentation soon.

**Comment by qwertygc** [comment]
Thank ! I don't know if is possible to automate a « changlog of sql » for the package ?
