### ISSUE TITLE
[need more testing] Caddy webserver

### ISSUE THREAD

**Issue by j0k3r** [wallabag/doc#35]
_From @Rurik19 on July 28, 2017 6:38_

I run wallabagger v2.2.3 on caddy server v0.10.4 with config just like that:
```
yourdomain.ru {
  root /var/www/wallabagger/web
  fastcgi / /var/run/php7-fpm.sock php {
    index app.php
  }
  rewrite / {
    to {path} {path}/ /app.php?{query}
  }
  tls your@emai.ru
  log /var/log/caddy/wbg.access.log
  errors /var/log/caddy/wbg.error.log
}
```
Both UI and API works like a charm. If somebody else test it, we should add it to the docs

_Copied from original issue: wallabag/wallabag#3295_

**Comment by Rurik19** [comment]
Should I chande the doc? I can make english and french version

**Comment by j0k3r** [comment]
Yeah of course you can

**Comment by nicosomb** [comment]
Can we close this issue?

**Comment by Rurik19** [comment]
Sure, we can :smile:
