### ISSUE TITLE
wallabag can't retrieve contents for this article

### ISSUE THREAD

**Issue by will-tam** [wallabag/doc#49]
Hello.

After trying to keep this [https://www.grafikart.fr/tutoriels/divers/json-web-token-presentation-958](https://www.grafikart.fr/tutoriels/divers/json-web-token-presentation-958), wallabag doesn't want retreive the content of this site.

I have tried with **f43.me** as explain in [troubleshoot this issue.](troubleshoot this issue.).

It works, but with the _external_ parser.

Best regards.

**Comment by j0k3r** [comment]
This issue was moved to wallabag/wallabag#3370

**Comment by j0k3r** [comment]
Issue like that should be created on the main repo of wallabag, not in the doc one.
I've moved the issue.
