### ISSUE TITLE
Installation is taking too much of ram

### ISSUE THREAD

**Issue by js-d-coder** [wallabag/doc#73]
Hi,  
I am trying to install latest version of this software on my Raspberry Pi 2 B+ which has ram of only 1G. The problem is installation is taking too much of RAM, more than 1G, because of which installation is failing. Is there a way to limit the amount of RAM for `mak`ing process?  

PHP 7.0.30-0+deb9u1, apache2 2.4.25-3+deb9u5 on raspbian based on debian stretch.

Thanks

**Comment by j0k3r** [comment]
How do you install it?

**Comment by js-d-coder** [comment]
I simply cloned the repo and then ran `make install` @j0k3r

**Comment by j0k3r** [comment]
You should better download it from here: https://static.wallabag.org/releases/
Deps are packaged in the tar file and it should required less ram.

**Comment by j0k3r** [comment]
This'll be solved in the 2.4 as the `composer.lock` is commited again. Composer will be much much faster and eat less memory.

See https://github.com/wallabag/wallabag/pull/3985

**Comment by js-d-coder** [comment]
thanks
