### ISSUE TITLE
Broken alerts blocks on Gitbook

### ISSUE THREAD

**Issue by techexo** [wallabag/doc#83]
Hi everyone,

There is an issue with the `alerts` plugin on GitBook, with following blocks being not detected as separated, and consequently colors being weird and so on.

Two `info` blocks separated by a blank line should be separated:
![image](https://user-images.githubusercontent.com/1850197/49942610-169b2680-fee6-11e8-973b-47c81ccd4b32.png)

One `info` and one `warn` blocks share the color of the latter:
![image](https://user-images.githubusercontent.com/1850197/49942623-2155bb80-fee6-11e8-8df3-ada08f80afaa.png)

I really like those blocks as they pop really well in a page, but it's a shame that they're not detected well. The plugin is not maintained anymore, maybe we should fall back on the [built-in warning system](https://docs.gitbook.com/content-editing/rich-content#hints-and-callouts) (even [if it's not well documented?](https://gitbook.canny.io/feature-requests/p/hints-callouts)).

There is not so much of these blocks, so I would be glad to make the change, if someone with access to the Gitbook interface can confirm that the following code is working without plugins on gitbook:
```
{% hint style="info" %}
Hello world
{% endhint %}
```

with style equal to `info`, `success`, `danger` or `warning`.

**Comment by j0k3r** [comment]
You can run the doc locally :)
https://github.com/wallabag/doc#install-it-locally

**Comment by techexo** [comment]
Yeah I know, but I had problems on my computer: the program breaks each time I save a file... 😅 I'll give it a try once again

**Comment by techexo** [comment]
@j0k3r What version are you using? On my computer, Gitbook breaks each time I update a file, and I basically have to remove everything already compiled to hope launching it again!

I also looked a bit more into it, and it seems that the `hint` blocks is actually part of another plugin (`hints`), also not updated anymore... It seems that the whole community of Gitbook is dying 😱 . I'll keep in touch if I succeed to do anything, but I am not beginning with big hopes.

**Comment by j0k3r** [comment]
Working version on my mac:

```
$ gitbook --version
CLI version: 2.3.2
GitBook version: 3.2.2
```

**Comment by techexo** [comment]
See PR https://github.com/wallabag/doc/pull/84.

**Comment by techexo** [comment]
I put that here for information:
![image](https://user-images.githubusercontent.com/1850197/49973046-d6fb2b80-ff33-11e8-9321-5857f0689d02.png)
