### ISSUE TITLE
Is keeping DE and IT doc right?

### ISSUE THREAD

**Issue by techexo** [wallabag/doc#88]
Hi everyone,

I was wondering if keeping the German (DE) and Italian (IT) documentation was still relevant... I don't think a lot of people willing to install wallabag on their/some server don't read English at all, and the translations seem to have dropped behind.

I can understand having the French one as most (all ?) of the core developers (and contributors?) are French. At some point, however, shouldn't we concentrate on fewer languages with better quality; and not have obsolete docs?

I don't want to bite the hand that feeds me (_cracher dans la soupe_), it's just that it seems like an interesting thinking to have.

**Comment by tcitworld** [comment]
We could add a warning on top of other translations than french and english to say that these versions are probably outdated.

**Comment by techexo** [comment]
Sounds like a good idea. I think a warning on top of all the pages would be the way to go (so people coming directly via a search engine will definitely see the warning)

**Comment by j0k3r** [comment]
I'm wondering if we should just remove them?
For example, I'm an italian who want to check something in the doc. If I see a message saying it's outdated, I won't read the italian version but the english one. Nope?

**Comment by techexo** [comment]
Honestly I think these extra translations are more a burden than useful: it's outdated, and I am pretty sure anyone wanting to actually host wallabag will speak at least technical English.

Could it be possible to "branch them out", so that someone wanting to update the whole doc could find them easily, but it isn't read by gitbook?

**Comment by j0k3r** [comment]
Maybe we should update the `LANGS.md` file and try locally.

**Comment by techexo** [comment]
@j0k3r cf also edit of my post above

**Comment by Kdecherf** [comment]
Hello there,
Do we have usage statistics of the documentation pages?

**Comment by techexo** [comment]
@Kdecherf Not that I know of. (But why would I? My answer is just a ping 😄)

**Comment by Kdecherf** [comment]
@techexo yeah, the question was for @j0k3r and @tcitworld :p

**Comment by j0k3r** [comment]
oh sorry, I've no idea :man_shrugging:

**Comment by techexo** [comment]
To reiterate my position, I think we should just keep one documentation, at least for the administration part.
I can understand keeping the FR one for the user part, as most users of wallabag.it are probably French, but the EN version is probably enough for people willing to install wallabag on a dedicated server.

If the EN version is sufficiently up-to-date, probably people will be willing to translate that in French and make a beautiful tutorial post on their blogs ;)

**Comment by j0k3r** [comment]
As per answer to the main question I think we can keep only the FR & EN up to date and remove other. I don't think keeping DE & IT translation of the outdated doc is good. Let's say an italian want to read the doc as soon as he'll see the message about _the doc probably outdated_ I think it'll go and check the english one.

Why bother reading the italian deprecated one while the english is up to date? :thinking:

**Comment by j0k3r** [comment]
I'm even thinking about removing the french documentation too.
It'll be less time consuming to translate the doc and it'll be faster for us to maintain it.

What do you think @wallabag/core ?

**Comment by tcitworld** [comment]
I would vote to keep them at least in this repo but make https://doc.wallabag.org/ redirect directly to https://doc.wallabag.org/en/.

Below the `The documentation is available in other languages:` line, we should add a big warning that it's not updated for other languages.

**Comment by matteocoder** [comment]
Long time no see guys! Feel free to remove the Italian documentation if you want.

**Comment by Kdecherf** [comment]
Hello everyone,

We've decided to remove FR, IT and DE translations during the rewrite of the documentation using hugo.

I'm closing this issue.
